version: '3.3'

services:

  asterisk:
    build: .
    image: flaviostutz/asterisk:17.9.3
    ports:
      - 5060:5060/udp
      - 5160:5160/udp
      - 18000-18100:18000-18100/udp
    restart: always

